"""
Django settings for aliseeker project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import socket


class CustomSocket(socket.socket):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        try:
            self.bind(('10.10.0.6', 0))
        except BaseException:
            pass

socket.socket = CustomSocket


import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5if(jwd94m(jzn^w^1tp6zz&@@r55_@jwa%kjl+h^^p5tg614v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['aliseeker.ddns.net', '104.248.108.67', 'localhost']
SECURE_SSL_REDIRECT = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'preferences',
    'admin_reorder',

    'main',
    'tickets',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'aliseeker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aliseeker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'aliseeker',
        'USER': 'regular',
        'PASSWORD': 'debian9-password',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'


ADMIN_REORDER = (
    {
        'app': 'main',
        'label': 'Информация',
        'models': [
            'main.BotUser',
            'main.Stats'
        ]
    },

    {
        'app': 'main',
        'label': 'AliExpress',
        'models': [
            'main.Notification'
        ]
    },

    {
        'app': 'main',
        'label': 'Финансы',
        'models': [
            'main.Input',
            'main.Output'
        ]
    },

    {
        'app': 'main',
        'label': 'Рассылка',
        'models': [
            'main.Post'
        ]
    },

    {
        'app': 'tickets',
        'label': 'Поддержка',
        'models': [
            'tickets.TicketDialogue'
        ]
    },

    {
        'app': 'main',
        'label': 'Настройки',
        'models': [
            'main.Texts',
            'main.Media',
            'main.Numbers'
        ]
    }
)


TELEGRAM_BOT_TOKEN = '771955071:AAEPbu9CiZqjis3kV3SMguUmZxnWkq1j8ZI'
TELEGRAM_WEBHOOK_PATH = f'bot{TELEGRAM_BOT_TOKEN}'

EPN_API_KEY = 'a1e9ab4f3a48014307011506198b4e51'
EPN_HASH = 'phipztduc8kwqrtz8uumj3o5hrdnpjag'

PAYEER_ACCOUNT = 'P1005374313'
PAYEER_API_ID = '670222993'
PAYEER_API_PASS = '28II9F6wp0VTgOrh'
PAYEER_PROXIES = {}

BOT_IS_COPY = False
BOT_ALERT_LIST = False
BOT_ENGLISH_AVAILABLE = False
BOT_NAME = 'AliSeeker'

TELEBOT_THREADED = False
BOT_SHOW_ERRORS = True

SHORT_LINK_SALT_LENGTH = 7

REQUESTS_TIMEOUT = 10
LINK_CHECKING_DELAY = 0.25
SEEKER_LINK_WAITING_DELAY = 0
MAX_OFFER_NAME_LENGTH = 50 + 3
MAX_AMOUNT_OF_OFFERS = 5

REFERRAL_PROGRAM_RATING_SIZE = 10

TICKETS_SUPPORT_TITLE = f'{BOT_NAME} Support'
TICKETS_BOT_TOKEN = TELEGRAM_BOT_TOKEN
TICKETS_TO_USER = 'main.BotUser'
TICKETS_TO_USER_URL_REVERSE = 'main_botuser'
TICKETS_MODULE_WITH_TELEBOT = 'main.bot'

PAYMENT_SYSTEMS = [
    ('💳 Payeer', 1136053, 'P1000000'),
    ('💳 QIWI RU', 26808, '+7953155XXXX'),
    ('💳 Yandex.Money RU', 57378077, '410011499718000'),
    ('💳 AdvCash', 87893285, 'advcash@payeer.com'),
    ('📞 Билайн RU', 24898938, '+79030001122'),
    ('📞 МегаФон RU', 24899391, '+79230001122'),
    ('📞 МТС RU', 24899291, '+79130001122'),
    ('📞 Tele2 RU', 95877310, '+79510001122')
]
PAYMENT_DELAY = 0
