# Generated by Django 2.1 on 2018-10-19 16:03

from django.db import migrations
import main.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181019_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='cost',
        ),
        migrations.AddField(
            model_name='settings',
            name='language_choice_button_en_label',
            field=main.models.preferences.BotButtonLabel(default='-', max_length=50, verbose_name='Кнопка выбора EN языка'),
        ),
        migrations.AddField(
            model_name='settings',
            name='language_choice_button_ru_label',
            field=main.models.preferences.BotButtonLabel(default='-', max_length=50, verbose_name='Кнопка выбора RU языка'),
        ),
        migrations.AddField(
            model_name='settings',
            name='language_choice_message',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Сообщение выбора языка'),
        ),
    ]
