# Generated by Django 2.1 on 2018-10-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_botuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'Английский'), ('ru', 'Русский')], default='', max_length=2),
        ),
    ]
