# Generated by Django 2.1 on 2018-10-19 17:13

from django.db import migrations
import main.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181019_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='feedback_message_en',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Сообщение обратной связи, RU'),
        ),
    ]
