# Generated by Django 2.1 on 2018-10-19 17:59

from django.db import migrations
import main.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181019_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='alert_list_button_label_en',
            field=main.models.preferences.BotButtonLabel(default='-', max_length=50, verbose_name='Кнопка оповещений, EN'),
        ),
        migrations.AddField(
            model_name='settings',
            name='alert_list_button_label_ru',
            field=main.models.preferences.BotButtonLabel(default='-', max_length=50, verbose_name='Кнопка оповещений, RU'),
        ),
    ]
