# Generated by Django 2.1 on 2018-10-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181019_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(default='', max_length=256, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, default='', max_length=256, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'Английский'), ('ru', 'Русский')], default='', max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID'),
        ),
    ]
