# Generated by Django 2.1 on 2018-10-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('main', '0012_auto_20181020_0712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Texts',
        ),
        migrations.AlterModelOptions(
            name='texts',
            options={'verbose_name': 'Тексты', 'verbose_name_plural': 'Тексты'},
        ),
    ]
