# Generated by Django 2.1 on 2018-10-20 08:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import main.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('main', '0013_auto_20181020_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('min_withdrawal_amount_rub', main.models.preferences.Price(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма вывода, RUB')),
                ('min_withdrawal_amount_usd', main.models.preferences.Price(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма вывода, USD')),
                ('referral_program_first_level_percent', main.models.preferences.Percent(decimal_places=2, max_digits=5, verbose_name='Процент 1-го уровня реферальной программы, %')),
                ('referral_program_second_level_percent', main.models.preferences.Percent(decimal_places=2, max_digits=5, verbose_name='Процент 2-го уровня реферальной программы, %')),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='texts',
            options={'verbose_name': 'Список', 'verbose_name_plural': 'Тексты'},
        ),
    ]
