# Generated by Django 2.1 on 2018-10-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181020_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numbers',
            options={'verbose_name': 'Список', 'verbose_name_plural': 'Числа'},
        ),
    ]
