# Generated by Django 2.1 on 2018-10-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20181020_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Имя'),
        ),
    ]
