# Generated by Django 2.1 on 2018-10-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20181020_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('en', 'Английский'), ('ru', 'Русский')], max_length=2, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
