# Generated by Django 2.1 on 2018-10-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_botuser_inviter'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='total_amount_of_notifications',
            field=models.IntegerField(default=0, verbose_name='Общее количество отслеживаний'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_amount_of_searches',
            field=models.IntegerField(default=0, verbose_name='Общее количество поисков'),
        ),
    ]
