# Generated by Django 2.1 on 2018-10-20 10:13

from django.db import migrations
import main.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20181020_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='balance',
            field=main.models.models.Money(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_earned',
            field=main.models.models.Money(decimal_places=2, default=0, max_digits=10, verbose_name='Всего заработано'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_withdrawn',
            field=main.models.models.Money(decimal_places=2, default=0, max_digits=10, verbose_name='Всего выведено'),
        ),
    ]
