# Generated by Django 2.1 on 2018-10-20 10:26

from django.db import migrations
import main.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20181020_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='total_earned',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='total_withdrawn',
        ),
        migrations.AddField(
            model_name='botuser',
            name='balance_rub',
            field=main.models.models.Money(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс, RUB'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='balance_usd',
            field=main.models.models.Money(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс, USD'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_earned_rub',
            field=main.models.models.Money(decimal_places=2, default=0, max_digits=10, verbose_name='Всего заработано, RUB'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_earned_usd',
            field=main.models.models.Money(decimal_places=2, default=0, max_digits=10, verbose_name='Всего заработано, USD'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_withdrawn_rub',
            field=main.models.models.Money(decimal_places=2, default=0, max_digits=10, verbose_name='Всего выведено, RUB'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_withdrawn_usd',
            field=main.models.models.Money(decimal_places=2, default=0, max_digits=10, verbose_name='Всего выведено, USD'),
        ),
    ]
