# Generated by Django 2.1 on 2018-10-20 11:01

from django.db import migrations
import main.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20181020_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='seeker_link_message_en',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Просьба прислать ссылку, EN'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_link_message_ru',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Просьба прислать ссылку, RU'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_link_waiting_message_en',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Сообщение об ожидании, EN'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_link_waiting_message_ru',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Сообщение об ожидании, RU'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_link_wrong_message_en',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Сообщение о неверной ссылке, EN'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_link_wrong_message_ru',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Сообщение о неверной ссылке, RU'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_notification_done_message_en',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Сообщение об отслеживании, EN'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_notification_done_message_ru',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Сообщение об отслеживании, RU'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_notification_proposal_button_label_en',
            field=main.models.preferences.BotButtonLabel(default='-', max_length=50, verbose_name='Кнопка предложения об отслеживании, EN'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_notification_proposal_button_label_ru',
            field=main.models.preferences.BotButtonLabel(default='-', max_length=50, verbose_name='Кнопка предложения об отслеживании, RU'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_notification_proposal_message_en',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Предложение об отслеживании, EN'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_notification_proposal_message_ru',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Предложение об отслеживании, RU'),
        ),
    ]
