# Generated by Django 2.1 on 2018-10-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20181020_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='last_action',
            field=models.CharField(default='created', max_length=16),
        ),
    ]
