# Generated by Django 2.1 on 2018-10-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_botuser_last_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='last_action',
            field=models.CharField(default='created', max_length=64),
        ),
    ]
