# Generated by Django 2.1 on 2018-10-20 12:54

from django.db import migrations
import main.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20181020_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='seeker_found_orders_message_en',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Сообщение о найденных товарах, EN'),
        ),
        migrations.AddField(
            model_name='texts',
            name='seeker_found_orders_message_ru',
            field=main.models.preferences.BotMessage(default='-', max_length=4000, verbose_name='Сообщение о найденных товарах, RU'),
        ),
    ]
