# Generated by Django 2.1 on 2018-10-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Оповещение', 'verbose_name_plural': 'Оповещения'},
        ),
    ]
