# Generated by Django 2.1 on 2018-10-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20181020_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('active', 'Отслеживается'), ('expired', 'Истекло')], default='active', max_length=7, verbose_name='Статус'),
        ),
    ]
