# Generated by Django 2.1 on 2018-10-21 15:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20181020_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (часовой пояс UTC)')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('postponed', 'Отложен'), ('queue', 'В очереди'), ('process', 'Рассылается'), ('done', 'Разослан')], default='created', max_length=9, verbose_name='Статус')),
                ('text', models.TextField(max_length=4000, verbose_name='Форматированный текст')),
                ('postpone', models.BooleanField(default=False, verbose_name='Отложить')),
                ('postpone_time', models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='Время публикации (часовой пояс UTC)')),
                ('amount_of_receivers', models.IntegerField(blank=True, null=True, verbose_name='Количество пользователей, получивших пост')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания (часовой пояс UTC)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Первый запуск бота (часовой пояс UTC)'),
        ),
    ]
