# Generated by Django 2.1 on 2018-10-23 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import main.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('main', '0033_auto_20181021_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('welcome_gif_en', main.models.preferences.GIF(null=True, upload_to=main.models.preferences.GIF.get_path, validators=[main.models.preferences.GIF.validate], verbose_name='Приветственная GIF-ка, EN')),
                ('welcome_gif_ru', main.models.preferences.GIF(null=True, upload_to=main.models.preferences.GIF.get_path, validators=[main.models.preferences.GIF.validate], verbose_name='Приветственная GIF-ка, RU')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Медиа',
            },
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='segmentation_all',
            field=models.BooleanField(default=True, verbose_name='Все пользователи'),
        ),
        migrations.AddField(
            model_name='post',
            name='segmentation_en',
            field=models.BooleanField(default=False, verbose_name='Англоязычные'),
        ),
        migrations.AddField(
            model_name='post',
            name='segmentation_ru',
            field=models.BooleanField(default=False, verbose_name='Русскоязычные'),
        ),
        migrations.AddField(
            model_name='post',
            name='segmentation_with_referrals',
            field=models.BooleanField(default=False, verbose_name='С рефералами'),
        ),
        migrations.AddField(
            model_name='post',
            name='segmentation_without_referrals',
            field=models.BooleanField(default=False, verbose_name='Без рефералов'),
        ),
    ]
