# Generated by Django 2.1 on 2018-10-23 13:44

from django.db import migrations
import main.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20181023_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='welcome_gif_en',
            field=main.models.preferences.GIF(blank=True, null=True, upload_to=main.models.preferences.GIF.get_path, validators=[main.models.preferences.GIF.validate], verbose_name='Приветственная GIF-ка, EN'),
        ),
        migrations.AlterField(
            model_name='media',
            name='welcome_gif_ru',
            field=main.models.preferences.GIF(blank=True, null=True, upload_to=main.models.preferences.GIF.get_path, validators=[main.models.preferences.GIF.validate], verbose_name='Приветственная GIF-ка, RU'),
        ),
    ]
