# Generated by Django 2.1 on 2018-10-23 18:32

from django.db import migrations, models
import main.models.models
import main.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20181023_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='segmentation_all',
        ),
        migrations.AlterField(
            model_name='media',
            name='welcome_gif_en',
            field=main.models.preferences.GIF(blank=True, null=True, upload_to=main.models.preferences.MediaFile.get_path, validators=[main.models.preferences.MediaFile.validate_media], verbose_name='Приветственная GIF-ка, EN'),
        ),
        migrations.AlterField(
            model_name='media',
            name='welcome_gif_ru',
            field=main.models.preferences.GIF(blank=True, null=True, upload_to=main.models.preferences.MediaFile.get_path, validators=[main.models.preferences.MediaFile.validate_media], verbose_name='Приветственная GIF-ка, RU'),
        ),
        migrations.AlterField(
            model_name='media',
            name='welcome_video_en',
            field=main.models.preferences.Video(blank=True, null=True, upload_to=main.models.preferences.MediaFile.get_path, validators=[main.models.preferences.MediaFile.validate_media], verbose_name='Приветственное MP4 видео, EN'),
        ),
        migrations.AlterField(
            model_name='media',
            name='welcome_video_ru',
            field=main.models.preferences.Video(blank=True, null=True, upload_to=main.models.preferences.MediaFile.get_path, validators=[main.models.preferences.MediaFile.validate_media], verbose_name='Приветственное MP4 видео, RU'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=main.models.models.Image(blank=True, null=True, upload_to=main.models.models.Image.get_path, validators=[main.models.models.Image.validate_image], verbose_name='Изображение снизу (до 1МБ)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='segmentation_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('all', 'Русский + Английский')], default='all', max_length=3, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='post',
            name='segmentation_referrals',
            field=models.CharField(choices=[('without', 'Без рефералов'), ('with', 'С рефералами'), ('all', 'Без рефералов + С рефералами')], default='all', max_length=7, verbose_name='Реферальная активность'),
        ),
    ]
