# Generated by Django 2.1 on 2018-10-26 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0059_auto_20181026_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.BooleanField(default=True)),
                ('last_message_sender', models.CharField(choices=[('user', 'Пользователь'), ('support', 'Поддержка')], default='user', max_length=7, verbose_name='Отправитель последнего сообщения')),
                ('last_message_time', models.DateTimeField(default=datetime.datetime(2018, 10, 26, 7, 52, 15, 98414, tzinfo=utc), verbose_name='Время последнего сообщения (часовой пояс UTC)')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=7, verbose_name='Статус')),
                ('marked', models.BooleanField(default=False, verbose_name='Избранный')),
                ('ignored', models.BooleanField(default=False, verbose_name='Игнор')),
                ('form_message', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Текст (форматированный)')),
                ('form_button_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки')),
                ('form_button_link', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
                ('form_image', tickets.models.Image(blank=True, null=True, upload_to=tickets.models.Image.get_path, validators=[tickets.models.Image.validate_image], verbose_name='Изображение (до 1 МБ)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue', to='main.BotUser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
